import React from 'react';

export const TermsPage: React.FC = () => {
  return (
    <div className="pt-24 pb-20 bg-slate-50 min-h-screen">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 bg-white p-12 rounded-xl shadow-sm border border-slate-200">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-slate-500 mb-8">Effective Date: October 24, 2025</p>
        
        <div className="prose prose-slate max-w-none text-slate-700">
            <h3 className="text-xl font-bold text-slate-900 mt-6 mb-4">1. Agreement to Terms</h3>
            <p className="mb-4">
                By accessing or using the website operated by Wall Art Mockup Engine ("we," "us," or "our"), you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
            </p>

            <h3 className="text-xl font-bold text-slate-900 mt-8 mb-4">2. Intellectual Property Rights</h3>
            <p className="mb-4">
                <strong>Our IP:</strong> The Service and its original content, features, and functionality are and will remain the exclusive property of Wall Art Mockup Engine and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries.
            </p>
            <p className="mb-4">
                <strong>Your Content:</strong> You retain all rights to any images or artwork you upload to the Service ("User Content"). By uploading User Content, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, and process your User Content solely for the purpose of providing the Services to you (i.e., generating mockups). We do not claim ownership of your artwork.
            </p>

            <h3 className="text-xl font-bold text-slate-900 mt-8 mb-4">3. Commercial Usage License</h3>
            <p className="mb-4">
                Subject to your compliance with these Terms and your payment of any applicable fees, Wall Art Mockup Engine grants you a non-exclusive, non-transferable license to use the images generated by the Service ("Generated Mockups") for commercial purposes, including marketing, advertising, and product listings on e-commerce platforms.
            </p>
            <p className="mb-4">
                <strong>Restrictions:</strong> You may not (i) resell, redistribute, or sublicense the Generated Mockups as standalone stock photography or digital assets; (ii) use the Generated Mockups in a way that competes with the Service; or (iii) use the Service for any illegal or unauthorized purpose.
            </p>

            <h3 className="text-xl font-bold text-slate-900 mt-8 mb-4">4. Accounts and Subscription</h3>
            <p className="mb-4">
                When you create an account with us, you must provide us information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account.
            </p>
            <p className="mb-4">
                <strong>Billing:</strong> You agree to pay all fees or charges to your account in accordance with the fees, charges, and billing terms in effect at the time a fee or charge is due and payable. Subscription fees are billed in advance and are non-refundable except as required by law.
            </p>
            <p className="mb-4">
                <strong>Cancellation:</strong> You may cancel your subscription at any time. Your cancellation will take effect at the end of the current paid term.
            </p>

            <h3 className="text-xl font-bold text-slate-900 mt-8 mb-4">5. Limitation of Liability</h3>
            <p className="mb-4">
                In no event shall Wall Art Mockup Engine, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage.
            </p>

            <h3 className="text-xl font-bold text-slate-900 mt-8 mb-4">6. Termination</h3>
            <p className="mb-4">
                We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease.
            </p>

            <h3 className="text-xl font-bold text-slate-900 mt-8 mb-4">7. Governing Law</h3>
            <p className="mb-4">
                These Terms shall be governed and construed in accordance with the laws of Delaware, United States, without regard to its conflict of law provisions.
            </p>

            <h3 className="text-xl font-bold text-slate-900 mt-8 mb-4">8. Contact</h3>
            <p className="mb-4">
                For any questions regarding these Terms, please contact us at legal@wallartengine.com.
            </p>
        </div>
      </div>
    </div>
  );
};